kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql-statefulset
  namespace: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  templates:
    metadata:
      labels: mysql
      spec:
        containers:
          - name: mysql
            image: mysql:9.0
            ports:
              - containerPort: 3306
            env:
              - name: MY_SQL_ROOT_PASSWORD
                value: "root"

