kind: VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1
metadata:
  name: apache-vpa
  namespace: apache
spec:
  targetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: apache-deployment
  updatePolicy:
    updateMode: "Auto"
